---
- block:
  - name: install git package
    apt:
      name: "git"
  - name: fetch gitea binary                                                                                                       
    get_url:                                                                                                                       
      url: "https://dl.gitea.io/gitea/{{ gitea_version }}/gitea-{{ gitea_version }}-linux-amd64"                                                               
      dest: "/usr/local/bin/gitea"                                                                                                 
      mode: "0755"
  - name: setup gitea environment
    script: "setup_gitea_env.sh"
  - name: install systemd service
    copy:
      src: "gitea.service"
      dest: "/etc/systemd/system/gitea.service"
      owner: "root"
      group: "root"
      mode: "0644"
  - name: enable and start gitea service
    systemd:
      daemon_reload: "yes"
      name: "gitea"
      state: "started"
      enabled: "yes"
  - name: setup nginx config
    template:
      src: "nginx.j2"
      dest: "/etc/nginx/sites-available/{{ gitea_domain_name }}"
      owner: "root"
      group: "root"
      mode: "0644"
  - name: restart nginx
    systemd:
      name: "nginx.service"
      state: "restarted"
  tags:
    - gitea
