---
- block:
  - name: install git and pymysql packages
    apt:
      name:
        - git
        - python-pymysql
  - name: fetch gitea binary
    get_url:
      url: "https://dl.gitea.io/gitea/{{ gitea_version }}/gitea-{{ gitea_version }}-linux-amd64"
      dest: "/usr/local/bin/gitea"
      mode: "0755"
  - name: create gitea user group
    group:
      name: git
      state: present
  - name: create gitea user account
    user:
      name: git
      password: "*"
      system: yes
      home: /home/git
      shell: /bin/bash
      groups: git
      state: present
  - name: create gitea meta data dir
    file:
      path: /var/lib/gitea
      state: directory
      owner: git
      group: git
      mode: "0750"
  - name: create gitea meta data subdir
    file:
      path: "/var/lib/gitea/{{ item }}"
      state: directory
      owner: git
      group: git
      mode: "0750"
    loop:
      - custom
      - data
      - log
  - name: create gitea config dir
    file:
      path: "/etc/gitea"
      state: directory
      owner: "root"
      group: "git"
      mode: "0770"
  - name: create gitea db
    mysql_db:
      login_unix_socket: "/var/run/mysqld/mysqld.sock"
      name: "{{ gitea_db_name }}"
      encoding: "utf8mb4"
      state: "present"
  - name: create gitea db account
    mysql_user:
      login_unix_socket: "/var/run/mysqld/mysqld.sock"
      name: "{{ gitea_db_user }}"
      password: "{{ gitea_db_password }}"
      priv: "{{ gitea_db_name}}.*:ALL"
      state: "present"
    no_log: "yes"
  - name: install systemd service
    copy:
      src: "gitea.service"
      dest: "/etc/systemd/system/gitea.service"
      owner: "root"
      group: "root"
      mode: "0644"
  - name: enable and start gitea service
    systemd:
      daemon_reload: "yes"
      name: "gitea"
      state: "started"
      enabled: "yes"
  - name: setup nginx config
    template:
      src: "nginx.j2"
      dest: "/etc/nginx/sites-available/{{ gitea_domain_name }}"
      owner: "root"
      group: "root"
      mode: "0644"
  - name: restart nginx
    systemd:
      name: "nginx.service"
      state: "restarted"
  tags:
    - gitea
